### ISSUE TITLE
获取accessToken时发生错误（拒绝访问）

### ISSUE THREAD

**Issue by akchiji888** [Xcube-Studio/Natsurainko.FluentCore#12]
System.Net.HttpListenerException
  HResult=0x80004005
  Message=拒绝访问。
  Source=System.Net.HttpListener
  StackTrace:
   在 System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   在 System.Net.HttpListener.AddAllPrefixes()
   在 System.Net.HttpListener.Start()
   在 Natsurainko.FluentCore.Extension.Windows.Module.Authenticator.MicrosoftAuthenticatorExtension.<GetAccessCode>d__0.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 MCL_Dev.ZhuYe.<startGame>d__3.MoveNext() 在 C:\Users\wodes\source\repos\MCL-Dev\ZhuYe.xaml.cs 中: 第 91 行

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]
    MCL_Dev.ZhuYe.startGame() (位于 ZhuYe.xaml.cs 中)

**Comment by natsurainko** [comment]
需要提供更具体的代码实现

**Comment by akchiji888** [comment]
var microsoftAuthenticator = new MicrosoftAuthenticator();
                    await microsoftAuthenticator.GetAccessCode(); // 调用系统默认浏览器取回验证令牌 需要 Natsurainko.FluentCore 的 Windows 扩展
                    var account = await microsoftAuthenticator.AuthenticateAsync(); // 验证账户
                    // 将验证得到的账户 添加到启动 方法 1
                    var setting = new LaunchSetting(new JvmSetting(javaPath));
                    setting.Account = account;
                    var launcher = new MinecraftLauncher(setting, locator);

**Comment by natsurainko** [comment]
需要设置 MicrosoftAuthenticator 的属性 ClientId以及RedirectUri

需要设置类似于这样的值 你需要注册Azure门户 然后得到你自己的ClientId 并在Azure中设置回调Url与RedirectUri相同
public const string ClientId = "00000000-0000-0000-0000-000000000000";
public const string RedirectUri = "http://localhost:5001/fluentlauncher/auth-response";

**Comment by akchiji888** [comment]
ok

**Comment by akchiji888** [comment]
我这次设定了clientId与RedirectUri，但依旧提示拒绝访问
```
var authenticator = new MicrosoftAuthenticator();
                    authenticator.ClientId = "dd09ec86-031b-4429-adb8-7fec6bc1fd79";
                    authenticator.RedirectUri = "https://login.live.com/oauth20_desktop.srf";
                    await authenticator.GetAccessCode();
                    var launcher = new MinecraftLauncher(launchSetting, authenticator, locator);
                    using var launchResponse = launcher.LaunchMinecraft(core);
```

**Comment by akchiji888** [comment]
（复制后缩进有点不太对，但程序里是正常的缩进）

**Comment by akchiji888** [comment]
问题解决了，提了管理员权限后就ok了

**Comment by natsurainko** [comment]
RedirectUri = "https://login.live.com/oauth20_desktop.srf";这里是要填一个本地的地址才有用的
