### ISSUE TITLE
使用Nuget提示安装失败的问题

### ISSUE THREAD

**Issue by PowerAngelXD** [Xcube-Studio/Natsurainko.FluentCore#14]
![QQ截图20230722203553](https://github.com/Xcube-Studio/Natsurainko.FluentCore/assets/63438232/8409d288-30a1-4c91-b83d-81a1c3c9c12a)
使用了.NET Core6.0与7.0安装该库一直提示版本不匹配

**Comment by natsurainko** [comment]
这个扩展要求了windows平台支持

**Comment by natsurainko** [comment]
.net7的项目要改成.net7-windows

**Comment by PowerAngelXD** [comment]
好的，感谢
