### ISSUE TITLE
微软登陆和mojang登陆gkd

### ISSUE THREAD

**Issue by xuanmou** [Xcube-Studio/Natsurainko.FluentCore#4]
微软登陆和mojang登陆gkd微软登陆和mojang登陆gkd微软登陆和mojang登陆gkd微软登陆和mojang登陆gkd微软登陆和mojang登陆gkd微软登陆和mojang登陆gkd微软登陆和mojang登陆gkd微软登陆和mojang登陆gkd微软登陆和mojang登陆gkd微软登陆和mojang登陆gkd微软登陆和mojang登陆gkd微软登陆和mojang登陆gkd微软登陆和mojang登陆gkd微软登陆和mojang登陆gkd微软登陆和mojang登陆gkd微软登陆和mojang登陆gkd微软登陆和mojang登陆gkd微软登陆和mojang登陆gkd微软登陆和mojang登陆gkd

**Comment by xingxing2008** [comment]
此项目已解决awa
